name: Docker Image CI

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#   watch:
#     types: started

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{rivieras}}
        DOCKER_PASSWORD: ${{aa123456}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rivieras/textwordexplain:latest
      
    - name: Docker Push
      run: docker push rivieras/textwordexplain
